spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:h2:mem:proddb
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        sql: error